# Generated by Django 5.0.6 on 2025-11-18 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('termometro', models.PositiveSmallIntegerField(default=3)),
                ('responsavel', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7)),
                ('entrada', models.DateField()),
                ('saida', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('permuta', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('razao', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Transferência'), ('SAIDA', 'Saída')], max_length=20)),
                ('responsavel_anterior', models.CharField(max_length=100)),
                ('responsavel_novo', models.CharField(blank=True, max_length=100)),
                ('data_transicao', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('motivo_saida', models.CharField(blank=True, max_length=255)),
                ('razao_saida', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='clientes.client')),
            ],
        ),
    ]
