# Generated by Django 5.0.6 on 2025-11-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_reference_tables_and_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-entrada', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='clienthistory',
            options={'ordering': ['-data_transicao']},
        ),
    ]
