# Generated by Django 5.0.6 on 2025-11-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_unify_motivos_razoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienthistory',
            name='tipo',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferência'), ('SAIDA', 'Saída'), ('TERMOMETRO', 'Termômetro'), ('VALOR', 'Valor/Permuta')], max_length=20),
        ),
    ]
