# Generated by Django 5.0.6 on 2025-11-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0006_alter_clienthistory_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="quer_alinhamento",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Consultor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ReuniaoPreferencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ALINHAMENTO", "Alinhamento"), ("FECHAMENTO", "Fechamento")], max_length=15
                    ),
                ),
                ("dia_pref_inicio", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("dia_pref_fim", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "horario_pref",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MANHA_PRIMEIRO", "Manhã - Primeiro horário"),
                            ("MANHA", "Manhã"),
                            ("TARDE", "Tarde"),
                            ("NOITE", "Noite"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ESCRITORIO_NORTE", "Escritório (Norte)"),
                            ("ESCRITORIO_SUL", "Escritório (Sul)"),
                            ("VIDEO", "Videoconferência"),
                            ("CLIENTE", "No cliente"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("local_descricao", models.CharField(blank=True, max_length=255)),
                ("duracao_minutos", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("data_sugerida", models.DateField(blank=True, null=True)),
                ("responsavel_nome", models.CharField(blank=True, max_length=100)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias_reuniao",
                        to="clientes.client",
                    ),
                ),
                (
                    "consultor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reunioes",
                        to="clientes.consultor",
                    ),
                ),
            ],
            options={
                "ordering": ["client__nome", "tipo"],
                "unique_together": {("client", "tipo")},
            },
        ),
    ]
