# Generated by Django 5.0.6 on 2025-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_consultor_reuniaopreferencia_client_quer_alinhamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniaopreferencia',
            name='horario_pref',
            field=models.CharField(blank=True, choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=30),
        ),
    ]
