# Generated by Django 5.0.6 on 2025-12-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_reuniaopreferencia_horario_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniaopreferencia',
            name='local',
            field=models.CharField(blank=True, choices=[('ESCRITORIO', 'Escritório'), ('ONLINE', 'Reunião Online'), ('CLIENTE', 'No cliente'), ('OUTRO', 'Outro')], max_length=30),
        ),
    ]
