# Generated by Django 5.0.6 on 2025-12-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_reuniaopreferencia_novos_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniaopreferencia',
            name='dia_semana_pref',
            field=models.CharField(blank=True, choices=[('SEGUNDA', 'Segunda-feira'), ('TERCA', 'Terça-feira'), ('QUARTA', 'Quarta-feira'), ('QUINTA', 'Quinta-feira'), ('SEXTA', 'Sexta-feira')], max_length=15),
        ),
    ]
