# Generated by Django 5.0.6 on 2025-12-08 18:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_reuniaopreferencia_dia_semana_pref'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoAlinhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.PositiveSmallIntegerField()),
                ('data_reuniao', models.DateField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_alinhamento', to='clientes.client')),
            ],
            options={
                'ordering': ['data_reuniao', 'client__nome'],
                'unique_together': {('client', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='AgendamentoFechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.PositiveSmallIntegerField()),
                ('data_reuniao', models.DateField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_fechamento', to='clientes.client')),
            ],
            options={
                'ordering': ['data_reuniao', 'client__nome'],
                'unique_together': {('client', 'mes', 'ano')},
            },
        ),
    ]
